---
pkg_dir: packages
log_dir: logs
configs_dir: compiled
report_dir: reports
reports_children_dirs: [ build, debug ]

ansible_python_interpreter: /home/johnsond/venvs/ansible/bin/python2.7

debug_dir: debug

report_type: full

domain_list: it-ninja.xyz

ansible_user: lab
ansible_ssh_pass: lab123

cisco_ssh:
  port: 22
  username: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"
  authorize: yes
  auth_password: "{{ ansible_ssh_pass }}"

netconf:
  port: 22
  transport: netconf
