---
- name: Assemble configurations
  assemble:
    src: "../{{ configs_dir }}/{{ inventory_hostname }}/"
    dest: "../{{ configs_dir }}/{{ inventory_hostname }}/999-candidate.conf"
  changed_when: False
  tags: [ print_action ]

- name: Remove lines beginning with '#'
  lineinfile:
    path: "../{{ configs_dir }}/{{ inventory_hostname }}/999-candidate.conf"
    regexp: '^#.+$'
    state: absent
  tags: [ print_action ]

- name: Executing Napalm Tasks (Generate diff)
  napalm_install_config:
    hostname: "{{ ansible_host|default(inventory_hostname) }}"
    username: "{{ ansible_user }}"
    dev_os: "{{ os }}"
    password: "{{ ansible_ssh_pass }}"
    config_file: "../{{ configs_dir }}/{{ inventory_hostname }}/999-candidate.conf"
    replace_config: true
    commit_changes: no
    diff_file: "../{{ configs_dir }}/{{ inventory_hostname }}/show-compare.diff"
  #no_log: true
  tags: [ print_action ]
