---
- name: Getter - IS-IS adjacency
  junos_command:
    commands: show isis adjacency
    display: text
    provider: "{{ netconf }}"
  register: getter_isis_adjacency
  changed_when: false
  tags: [ print_action ]
