---
- name: EVE-NG MPLS Topology - Ansible Playbook Test
  hosts: all
  connection: local
 
  pre_tasks:

    # - include: tasks/hostfile.yml
    #   name: Build hostfile

    - include: tasks/ssh-key-grab.yml
      vars:
        known_hosts: ~/.ssh/known_hosts
      name: Grab SSH keys
      tags: [ rollback ]

    - include: tasks/cleanup.yml
      name: Cleanup
      tags: [ rollback, print_action ]

    - name: Include variables
      include_vars: "{{ item }}"
      with_fileglob: [ "vars/*.yml" ]
      run_once: yes

  tasks:

    - name: Rollback to rescue configuration
      junos_config:
        src: .rescue-configs/{{ os }}/{{ inventory_hostname }}.conf
        src_format: set
        update: replace
        provider: "{{ netconf }}"
      when: rollback_rescue == '1'
      tags: [ rollback, print_action ]

- include: tasks/def_roles.yml
- include: tasks/assemble_push_conf.yml
