---
- name: EVE-NG MPLS Topology - Ansible Playbook Test
  hosts: all
  connection: local

  vars:
 
  pre_tasks:

    - include: tasks/hostfile.yml
      name: Build hostfile

    - include: tasks/ssh-key-grab.yml
      vars:
        known_hosts: ~/.ssh/known_hosts
      name: Grab SSH keys

      tags:
        - rollback

    - include: tasks/cleanup.yml
      name: Cleanup

  tasks:

    - name: Rollback MPLS to rescue
      junos_config:
        src: .rescue-configs/{{ inventory_hostname }}.conf
        src_format: set
        update: replace
        provider: "{{ netconf }}"
      when: rollback_rescue == '1' and 'junos' in group_names

      tags:
        - rollback
        - print_action

    - name: Rollback Cisco to rescue
      ios_config:
        src: .rescue-configs/{{ inventory_hostname }}.conf
        replace: block
        provider: "{{ cisco_ssh }}"
        save_when: always
      when: rollback_rescue == '1' and 'ios' in group_name

      tags:
        - rollback
        - print_action

    - include: tasks/cleanup.yml
      name: Cleanup

      tags:
        - rollback
        - print_action

# - include: tasks/get_facts.yml
- include: tasks/def_roles.yml
- include: tasks/assemble_push_conf.yml