---
- name: EVE-NG MPLS Verify Topology - Ansible Playbook Test
  hosts: all
  connection: local

  vars:
 
  pre_tasks:

    - include: tasks/hostfile.yml
      name: Build hostfile

    - include: tasks/ssh-key-grab.yml
      vars:
        known_hosts: ~/.ssh/known_hosts
      name: Grab SSH keys

      tags:
        - rollback

    - include: tasks/cleanup.yml
      name: Cleanup

  tasks:

    - command: date
      register: play_run_datetime
      run_once: true

    - name: Gather system operational information
      junos_command:
        commands: "{{ item }}"
        display: xml
        provider: "{{ netconf }}"
      with_items:
        - show isis adjacency
        - show isis interface
      register: gathered_data 

    - name: Verify System Operations
      template:
        src: templates/verify.j2
        dest: "{{ reports_dir }}/{{ inventory_hostname }}.txt"
