---
- name: EVE-NG MPLS Verify Network
  hosts: all
  connection: local

  vars:
 
  pre_tasks:

    # - include: hostfile.yml
    #   name: Build hostfile

    - include: tasks/ssh_key_grab.yml
      vars:
        known_hosts: ~/.ssh/known_hosts
    
    - include: tasks/import_vars.yml
      run_once: yes

    - command: date
      register: play_run_datetime
      run_once: true

- include: tasks/roles_verify_fabric.yml
