---
- name: Assmeble and Push Configuration
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    
    - name: Assemble configuration
      assemble: src=../{{ configs_dir }}/{{ inventory_hostname }}/ dest=../{{ configs_dir }}/{{ inventory_hostname }}/999-candidate.conf
      changed_when: False
      when: commit_changes | match('0')

      tags:
        - deploy

    - name: Remove temporary configuration files
      file: path=../{{ configs_dir }}/{{ inventory_hostname }}/*.out state=absent
      changed_when: False
      when: commit_changes | match('0')

      tags:
        - deploy

    - name: Executing Napalm Tasks
      napalm_install_config:
        hostname={{ inventory_hostname }}
        username={{ ansible_user }}
        dev_os={{ os }}
        password={{ ansible_ssh_pass }}
        config_file=../{{ configs_dir }}/{{ inventory_hostname }}/999-candidate.conf
        commit_changes={{ commit_changes }}
        diff_file=../{{ configs_dir }}/{{ inventory_hostname }}/show-compare.diff
      #no_log: true

      tags:
        - deploy
        - print_action
