---
- name: Populate hostfile
  blockinfile:
    path: /home/johnsond/.hosts
    marker: "# ----- {mark} ANSIBLE MANAGED BLOCK ----- #"
    block: |
      192.168.1.1 LAB-PE1
      192.168.1.2 LAB-PE2
      192.168.1.3 LAB-PE3
      192.168.1.4 LAB-PE4
      192.168.1.11 LAB-COR1
      192.168.1.12 LAB-COR2
      192.168.1.13 LAB-COR3
      192.168.1.14 LAB-COR4
  run_once: yes
  tags: [ rollback ]
  register: hostfile
  
- service:
    name: dnsmasq
    state: restarted
  delegate_to: localhost
  become: yes
  run_once: yes
  when: hostfile|changed
