---
- name: Remove Old Configuration
  file: 
    path: "{{ configs_dir }}/{{ inventory_hostname }}/"
    state: absent
  register: baseconfdir
  changed_when: False

- name: Create Empty Build Directory
  file: 
    path: "{{ baseconfdir.path }}"
    state: directory
  changed_when: False

- name: Include global play variables
  include_vars: "{{ item }}"
  with_fileglob: [ "../vars/*.yml" ]
  run_once: yes
