---
- name: Count passed tests
  shell: cat ../{{ report_dir }}/{{ inventory_hostname }}.txt | grep PASS | wc -l
  args:
    chdir: "{{ playbook_dir }}"
  register: pass_count

- name: Count failed tests
  shell: cat ../{{ report_dir }}/{{ inventory_hostname }}.txt | grep FAIL | wc -l
  args:
    chdir: "{{ playbook_dir }}"
  register: fail_count

- name: Add blank link to end of report
  lineinfile:
    path: "../{{ report_dir }}/{{ inventory_hostname }}.txt"
    line: "\n"
    insertafter: EOF
    state: present

- name: Start test summary block
  lineinfile:
    path: "../{{ report_dir }}/{{ inventory_hostname }}.txt"
    line: | 
      TEST SUMMARY
      ------------
    insertafter: EOF
    state: present

- name: Add passed tests to report
  lineinfile:
    path: "../{{ report_dir }}/{{ inventory_hostname }}.txt"
    line: "TESTS PASSED: {{ pass_count.stdout_lines[0] }}"
    insertafter: |
      TEST SUMMARY
      ------------
    state: present

- name: Add failed tests to report
  lineinfile:
    path: "../{{ report_dir }}/{{ inventory_hostname }}.txt"
    line: "TESTS FAILED: {{ fail_count.stdout_lines[0] }}"
    insertafter: '^TESTS PASSED:'
    state: present

- name: Add EOF block
  lineinfile:
    path: "../{{ report_dir }}/{{ inventory_hostname }}.txt"
    line: "\n\n---------------------------------------------- END OF REPORT ---------------------------------------------------------\n\n"
    insertafter: EOF
    state: present

# - replace:
#     path: "../{{ report_dir }}/{{ inventory_hostname }}.txt"
#     regexp: 'serial_number'
#     replace: "{{napalm_serial_number}}"

# - replace:
#     path: "../{{ report_dir }}/{{ inventory_hostname }}.txt"
#     regexp: 'software_ver'
#     replace: "{{napalm_os_version}}"