---
- include_vars: ../config_fabric/vars/main.yml

- name: Include getter modules
  include: "{{ item }}"
  with_fileglob: [ "getters/*.yml" ]

- name: Include test modules
  include: "{{ item }}"
  with_fileglob: [ "tests/*.yml" ]
