---
routing_options:
  router_id: 10.1.1.11
  autonomous_system: 0.65535
  dynamic_tunnels: true

loopback:
  name: lo0
  logical_attributes: {
    sub_iface: 0,
    inet: {
      enabled: true,
      address: 10.1.1.11
    },
    iso: {
      enabled: true,
      address: 49.0000.0172.0016.0011.00
    }
  }


fabric_interfaces:
  - { 
      name: em1,
      annotatation: 'link_index: 0 | LAB-COR1 em1.0 169.254.0.1/31 --> 169.254.0.0/31 em1.0 LAB-PE1',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-PE1 em1,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.1/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

  - { 
      name: em2,
      annotatation: 'link_index: 4 | LAB-COR1 em2.0 169.254.0.5/31 --> 169.254.0.4/31 em1.0 LAB-PE2',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-PE2 em1,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.5/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

  - { 
      name: em3,
      annotatation: 'link_index: 16 | LAB-COR1 em3.0 169.254.0.16/31 --> 169.254.0.17/31 em3.0 LAB-COR2',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-COR2 em3,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.16/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

  - { 
      name: em5,
      annotatation: 'link_index: 18 | LAB-COR1 em5.0 169.254.0.18/31 --> 169.254.0.19/31 em5.0 LAB-COR4',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-COR4 em5,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.18/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

  - { 
      name: em4,
      annotatation: 'link_index: 20 | LAB-COR1 em4.0 169.254.0.20/31 --> 169.254.0.21/31 em1.0 LAB-COR3',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-COR3 em1,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.20/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

  - { 
      name: em0,
      annotatation: 'link_index: 28 | LAB-COR1 em0.0 169.254.0.28/31 --> 169.254.0.29/31 em0.0 LAB-COR4',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-COR4 em0,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.28/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

