---
routing_options:
  router_id: 10.1.1.12
  autonomous_system: 0.65535
  dynamic_tunnels: true

loopback:
  name: lo0
  logical_attributes: {
    sub_iface: 0,
    inet: {
      enabled: true,
      address: 10.1.1.12
    },
    iso: {
      enabled: true,
      address: 49.0000.0172.0016.0012.00
    }
  }


fabric_interfaces:
  - { 
      name: em1,
      annotatation: 'link_index: 2 | LAB-COR2 em1.0 169.254.0.3/31 --> 169.254.0.2/31 em2.0 LAB-PE1',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-PE1 em2,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.3/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

  - { 
      name: em2,
      annotatation: 'link_index: 6 | LAB-COR2 em2.0 169.254.0.7/31 --> 169.254.0.6/31 em2.0 LAB-PE2',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-PE2 em2,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.7/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

  - { 
      name: em3,
      annotatation: 'link_index: 16 | LAB-COR2 em3.0 169.254.0.17/31 --> 169.254.0.16/31 em3.0 LAB-COR1',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-COR1 em3,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.17/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

  - { 
      name: em5,
      annotatation: 'link_index: 22 | LAB-COR2 em5.0 169.254.0.22/31 --> 169.254.0.23/31 em5.0 LAB-COR3',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-COR3 em5,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.22/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

  - { 
      name: em4,
      annotatation: 'link_index: 24 | LAB-COR2 em4.0 169.254.0.24/31 --> 169.254.0.25/31 em1.0 LAB-COR4',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-COR4 em1,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.24/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

