---
routing_options:
  router_id: 10.1.1.1
  autonomous_system: 0.65535
  dynamic_tunnels: true

loopback:
  name: lo0
  logical_attributes: {
    sub_iface: 0,
    inet: {
      enabled: true,
      address: 10.1.1.1
    },
    iso: {
      enabled: true,
      address: 49.0000.0172.0016.0001.00
    }
  }


fabric_interfaces:
  - { 
      name: em1,
      annotatation: 'link_index: 0 | LAB-PE1 em1.0 169.254.0.0/31 --> 169.254.0.1/31 em1.0 LAB-COR1',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-COR1 em1,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.0/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

  - { 
      name: em2,
      annotatation: 'link_index: 2 | LAB-PE1 em2.0 169.254.0.2/31 --> 169.254.0.3/31 em1.0 LAB-COR2',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-COR2 em1,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.2/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

