---
routing_options:
  router_id: 10.1.1.3
  autonomous_system: 0.65535
  dynamic_tunnels: true

loopback:
  name: lo0
  logical_attributes: {
    sub_iface: 0,
    inet: {
      enabled: true,
      address: 10.1.1.3
    },
    iso: {
      enabled: true,
      address: 49.0000.0172.0016.0003.00
    }
  }


fabric_interfaces:
  - { 
      name: em1,
      annotatation: 'link_index: 8 | LAB-PE3 em1.0 169.254.0.8/31 --> 169.254.0.9/31 em3.0 LAB-COR3',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-COR3 em3,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.8/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

  - { 
      name: em2,
      annotatation: 'link_index: 10 | LAB-PE3 em2.0 169.254.0.10/31 --> 169.254.0.11/31 em4.0 LAB-COR4',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-COR4 em4,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.10/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

