---
routing_options:
  router_id: 10.1.1.14
  autonomous_system: 0.65535
  dynamic_tunnels: true

loopback:
  name: lo0
  logical_attributes: {
    sub_iface: 0,
    inet: {
      enabled: true,
      address: 10.1.1.14
    },
    iso: {
      enabled: true,
      address: 49.0000.0172.0016.0014.00
    }
  }


fabric_interfaces:
  - { 
      name: em4,
      annotatation: 'link_index: 10 | LAB-COR4 em4.0 169.254.0.11/31 --> 169.254.0.10/31 em2.0 LAB-PE3',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-PE3 em2,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.11/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

  - { 
      name: em3,
      annotatation: 'link_index: 12 | LAB-COR4 em3.0 169.254.0.13/31 --> 169.254.0.12/31 em1.0 LAB-PE4',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-PE4 em1,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.13/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

  - { 
      name: em5,
      annotatation: 'link_index: 18 | LAB-COR4 em5.0 169.254.0.19/31 --> 169.254.0.18/31 em5.0 LAB-COR1',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-COR1 em5,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.19/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

  - { 
      name: em1,
      annotatation: 'link_index: 24 | LAB-COR4 em1.0 169.254.0.25/31 --> 169.254.0.24/31 em4.0 LAB-COR2',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-COR2 em4,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.25/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

  - { 
      name: em2,
      annotatation: 'link_index: 26 | LAB-COR4 em2.0 169.254.0.27/31 --> 169.254.0.26/31 em2.0 LAB-COR3',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-COR3 em2,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.27/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

  - { 
      name: em0,
      annotatation: 'link_index: 28 | LAB-COR4 em0.0 169.254.0.29/31 --> 169.254.0.28/31 em0.0 LAB-COR1',
      physical_attributes: {
        mtu: 2000,
        descr: WAN | LAB-COR1 em0,
      },
      logical_attributes: {
        sub_iface: 0,
        inet: {
          enabled: true,
          address: 169.254.0.29/31
        },
        iso: {
          enabled: true
        },
        cost: 5
      }
    }

